# Generated by Django 3.2.7 on 2021-09-11 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_desc', models.CharField(max_length=255)),
                ('full_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docstore.folder')),
                ('topics', models.ManyToManyField(to='docstore.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contents', models.BinaryField()),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docstore.folder')),
                ('topics', models.ManyToManyField(to='docstore.Topic')),
            ],
        ),
    ]
