# Generated by Django 3.2.7 on 2021-09-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_auto_20210912_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docstore.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='documents', to='docstore.Topic'),
        ),
    ]
